#!/usr/bin/env bash
# Check if correct number of arguments were passed
if [ "$#" -lt 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Set variables from command line arguments
file_path="$1"
server_ip="$2"
username="$3"
ssh_key_path="$4"

# Use scp to transfer the file to the server
scp -o StrictHostKeyChecking=no -i "$ssh_key_path" "$file_path" "$username"@"$server_ip":~

# Check if scp command was successful
if [ "$?" -eq 0 ]; then
  echo "File transferred successfully."
else
  echo "File transfer failed."
fi
